name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r ./geoipupdate/requirements.txt

      - name: Run Tests
        run: pytest
